{
 "title": "P4 Historical Stats",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "All P4 Cmds Completed Count (rate/10min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(p4_cmd_counter[10m]))" }
   ]
  },
  {
   "title": "Concurrent running cmds",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "p4_cmd_running" }
   ]
  },
  {
   "title": "p4d log lines read (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(p4_prom_log_lines_read[1m])"
    }
   ]
  },
  {
   "title": "p4 cmd count (top 20)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "topk(20,p4_cmd_counter[10m])", "legendFormat": "cmd={{cmd}}" }
   ]
  },
  {
   "title": "p4 cmd per user count (top 20)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,p4_cmd_user_counter[10m])"
    }
   ]
  },
  {
   "title": "Cmd Count and Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true
  },
  {
   "title": "p4 cmds top 10 (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_cmd_counter[1m])))"
    }
   ]
  },
  {
   "title": "Cmds duration (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(p4_cmd_cumulative_seconds[1m]))",
     "legendFormat": "{cmd=\"{{cmd}}\",serverid=\"{{serverid}}\"}}"
    }
   ]
  },
  {
   "title": "Top 20 cmd avg duration",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,p4_cmd_cumulative_seconds/p4_cmd_counter)",
     "legendFormat": "{cmd=\"{{cmd}}\",serverid=\"{{serverid}}\"}}"
    }
   ]
  },
  {
   "title": "Cmds per user duration (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(p4_cmd_user_cumulative_seconds[1m]))",
     "legendFormat": "{user=\"{{user}}\",serverid=\"{{serverid}}\"}}"
    }
   ]
  },
  {
   "title": "p4 cmds per user top 10 (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_cmd_user_counter[1m])))"
    }
   ]
  },
  { "title": "Table Locking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "p4 read locks held per table (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_total_read_held_seconds[1m])))"
    }
   ]
  },
  {
   "title": "p4 read locks waiting (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_total_read_wait_seconds[1m])))"
    }
   ]
  },
  {
   "title": "p4 write locks held per table (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_total_write_held_seconds[1m])))"
    }
   ]
  },
  {
   "title": "p4 write locks wait per table (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_total_write_wait_seconds[1m])))"
    }
   ]
  }
 ]
}